model/auth: Fixed exception in validate_password() method
TypeError: 'NoneType' object has no attribute '__getitem__'

self.password[:64] failed because self.password was None.